### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by wesafe1** [duynamrcv/rbf_bsmc#1]
When I ran the Adaptive/BSMC Attention Controller, there was an error displaying the Gain parameter. When I clicked on this module, I found that the signal and parameter properties in the lamdaa and gamma modules were not set, causing the entire Adaptive module to fail to run and unable to find load ('results/* *. mat ') during drawing. What should I do？

**Comment by duynamrcv** [comment]
You need to run ```parameter.m``` first to init all essential parameters. All *.mat files have been ignored to push on this repo. You need to run .xls file to save result data to .mat files.

**Comment by wesafe1** [comment]
Firstly, thank you for your reply. I followed the response you provided and proceeded with the operation. I first ran the parameter. m file and initialized and assigned various parameters of the system. Then, I ran the adapte.slx file and it ran successfully. Then I saw four datasets on the left side of the interface, namely ref.mat, dis.mat, est.mat, and pos.mat. Among them, pos.mat is a matrix of n rows and 6 columns that changes over time, and est.mat is a matrix of n rows and 3 columns that changes over time.
But in plod_results. m, it is necessary to import datasets, such as pos_1. mat ····· pos_6, mat, est_1, mat ···· est_3. mat. These datasets do not appear as pos_1. mat ·····pos_6, mat, est_1, mat ···· est_3. mat, only est. mat, pos.mat. What should I do in this situation?
I think it is precisely because of this reason that when I run other. m files, such as at_ref, at_dynamic, Iref. m, etc., I will encounter errors, and the error message is that the number of input parameters is insufficient.
Looking forward to your reply!

**Comment by duynamrcv** [comment]
The files `parameter.m` and `plot*.m` are script files, and the other `*.m` files are function files. On MATLAB IDE you will see they have different icons. Function files can not run singly without input variables, that is a reason why you get errors. 
By default in simulink, the collected data will be exported to .mat files under the default name, you can simply change the file name for visualization. In the `plot_*.m` file, I am comparing two algorithms, SMC and our, each algorithm will run 3 times corresponding to 3 UAVs in a  formation. You need to change the id of the UAV (1-3) and their initial position in simulink. You can easily change it for 1 UAV or other formations with different number and topology. You can also read and change scripts in `plot_result.m` for your purposes.

**Comment by wesafe1** [comment]
Thank you very much for your help. All the issues I mentioned above have been resolved, thank you very much. Wishing you smooth scientific research, good health, and happy every day!
